"""Genblaze image-generation adapter.

This is the ONLY module that imports the Genblaze SDK or talks to an image
provider. Per the AGENTS.md invariant "all external APIs wrapped in repo/",
everything provider-specific (the Genblaze Pipeline, the OpenAI DalleProvider,
and the HTTP/`file://` fetch of the generated bytes) stays contained here.

Design (see docs/features/image-generation.md):
  - Genblaze does generation ONLY. We run the pipeline WITHOUT a sink, so the
    asset's bytes land in a local temp dir (gpt-image-* returns base64 which
    Genblaze writes to a `file://` path) or behind a short-lived provider CDN
    URL (dall-e family). Either way we read the raw bytes here and hand them
    back to the service layer, which persists to B2 through `b2_client` — the
    single standards-compliant S3 client. We never add the genblaze-s3 sink
    (that would be a second S3 client / second user agent — see the plan).
  - The Genblaze canonical provenance manifest (with its `canonical_hash`) is
    returned alongside the bytes and stored in B2 in each pin's sidecar.
"""

import logging
import tempfile
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote, urlparse

import httpx
from genblaze_core import Modality, Pipeline
from genblaze_openai import DalleProvider
from PIL import Image

from app.config import settings

logger = logging.getLogger(__name__)

_IMAGE_SIZE = "1024x1024"
_FETCH_TIMEOUT_S = 60.0


@dataclass
class GeneratedImage:
    """Provider-agnostic result handed to the service layer."""

    image_bytes: bytes
    media_type: str
    width: int
    height: int
    sha256: str
    # The Genblaze canonical manifest (model_dump) + its canonical hash, so
    # the service can embed full provenance into the pin sidecar.
    manifest: dict
    canonical_hash: str


class ImageGenerationError(RuntimeError):
    """Raised when the provider call fails or returns no usable asset."""


def _read_asset_bytes(url: str) -> bytes:
    """Return the raw image bytes for a Genblaze asset URL.

    gpt-image-* writes base64 to a local temp file and reports a `file://`
    URL; dall-e returns a short-lived https CDN URL we fetch with httpx.
    """
    parsed = urlparse(url)
    if parsed.scheme == "file":
        path = Path(unquote(parsed.path))
        return path.read_bytes()
    if parsed.scheme in ("http", "https"):
        resp = httpx.get(url, timeout=_FETCH_TIMEOUT_S, follow_redirects=True)
        resp.raise_for_status()
        return resp.content
    raise ImageGenerationError(f"Unsupported asset URL scheme: {parsed.scheme!r}")


def _dimensions(image_bytes: bytes, fallback_w: int | None, fallback_h: int | None):
    """Best-effort (width, height); decode the bytes, falling back to the
    provider-reported dims if decode fails."""
    try:
        import io

        with Image.open(io.BytesIO(image_bytes)) as im:
            return im.width, im.height
    except Exception:
        return fallback_w or 0, fallback_h or 0


def generate_image(prompt: str) -> GeneratedImage:
    """Generate one image for `prompt` via Genblaze + OpenAI gpt-image-1.

    Runs a no-sink pipeline, reads the resulting bytes, computes the SHA-256
    and dimensions, and returns the canonical provenance manifest. Raises
    ImageGenerationError on any failure (missing key, provider error, etc.).
    """
    if not settings.openai_api_key:
        raise ImageGenerationError(
            "OPENAI_API_KEY is not set — image generation is unavailable."
        )

    # Temp dir for the decoded b64 PNG (gpt-image-*). Genblaze owns the file;
    # we read it back immediately and let the OS reap the temp dir.
    out_dir = tempfile.mkdtemp(prefix="moodboard-gen-")
    provider = DalleProvider(api_key=settings.openai_api_key, output_dir=out_dir)

    try:
        result = (
            Pipeline("moodboard-pin", project_id="ai-moodboard-generator")
            .step(
                provider,
                model="gpt-image-1",
                prompt=prompt,
                modality=Modality.IMAGE,
                size=_IMAGE_SIZE,
                quality=settings.moodboard_image_quality,
            )
            # raise_on_failure=True surfaces provider errors as exceptions
            # (forward-compatible with genblaze-core 0.4.0's default).
            .run(timeout=120, max_retries=1, raise_on_failure=True)
        )
    except ImageGenerationError:
        raise
    except Exception as e:  # genblaze PipelineError, provider/auth errors, etc.
        raise ImageGenerationError(f"Image generation failed: {e}") from e

    # PipelineResult exposes both `.run`/`.manifest` and tuple unpacking;
    # use attribute access and fall back to unpacking defensively.
    run = getattr(result, "run", None)
    manifest = getattr(result, "manifest", None)
    if run is None or manifest is None:
        run, manifest = result  # tuple shape

    if not run.steps or not run.steps[0].assets:
        raise ImageGenerationError("Provider returned no image asset.")

    step = run.steps[0]
    asset = step.assets[0]
    image_bytes = _read_asset_bytes(asset.url)
    if not image_bytes:
        raise ImageGenerationError("Generated asset was empty.")

    import hashlib

    sha256 = asset.sha256 or hashlib.sha256(image_bytes).hexdigest()
    width, height = _dimensions(image_bytes, asset.width, asset.height)

    return GeneratedImage(
        image_bytes=image_bytes,
        media_type=asset.media_type or "image/png",
        width=width,
        height=height,
        sha256=sha256,
        manifest=manifest.model_dump(mode="json"),
        canonical_hash=manifest.canonical_hash,
    )
